# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 387)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 190, 150, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 60, 54, 12))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(83, 40, 191, 71))
        self.textEdit.setObjectName("textEdit")
        self.openPathButton = QtWidgets.QPushButton(Form)
        self.openPathButton.setGeometry(QtCore.QRect(50, 170, 150, 23))
        self.openPathButton.setObjectName("pushButton")
        self.filePathlineEdit = QtWidgets.QLineEdit(self)
        self.filePathlineEdit.setObjectName("filePathlineEdit")
        self.filePathlineEdit.setGeometry(QtCore.QRect(200, 174, 300, 23))
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "生成二维码"))
        self.label.setText(_translate("Form", "请输入："))
        self.openPathButton.setText(_translate("Form", "选择生成的文件路径"))
